### ISSUE TITLE
Installing Theme

### ISSUE THREAD

**Issue by arlensot** [ThemeFuse/Scratch-Theme#9]
I'm uploading the theme with the wp installation.

I use the file here in github (master) and the one in your website (normal), but every time I've tried to do it, it says I don't have the style.css style sheet.

Instalando tema desde el archivo: Scratch-Theme-master.zip

DB Cache Reloaded Info: El caché no está habilitado. Visita la Página de Configuración para activarlo.

Descomprimiendo…

Instalando el tema…

No se ha podido descomprimir el paquete. El tema no tiene la hoja de estilo style.css.

Fallo en la instalación del tema.

Can you help me with this?

**Comment by moldcraft** [comment]
Our theme contains 2 themes: scratch-parent and scratch-child.
That script maybe tries to find the style.css fine in root directory, which in our zip doesn't exist.
Try to install the theme manually: Upload the zip via FTP and extract it in `themes/` directory.
Or extract the zip on your PC, then zip only the scratch-parent directory and upload/install it via admin panel.

**Comment by arlensot** [comment]
What's the difference between parent and child theme?

Thanks.

**Comment by moldcraft** [comment]
Parent theme usually is the one that the user buys and he is not changing anything in it. On theme update, that directory is replaced entirely with the new version.
To customize some files in parent theme, the user creates (or activates if it already exists) the child theme and creates the desired files in it, those files will replace (will be loaded instead of) parent theme files. Child theme is almost empty and it doesn't work without parent theme.

https://codex.wordpress.org/Child_Themes

P.S. You are a beginner or you developed themes for some other cms (for e.g. joomla, drupal) ?

**Comment by arlensot** [comment]
Beginner:person_frowning:, and thanks for the explanation.
